[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --cov=janus --cov-report=term-missing
# Ignore these files as they require specific external environments (K8s, SENSE auth)
norecursedirs = .git
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20
